import { useEffect, useMemo, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { AppShell, PageHeader } from '../../components/AppShell';
import { Icon } from '../../components/Icon';
import { partnersApi } from '../../lib/partnersApi';
import { useAuthStore } from '../../store/useAuthStore';
import { PARTNER_STATUS_LABELS, PARTNER_TYPE_LABELS, type Partner, type PartnerFilters } from '../../types/partners';

type SortKey = 'name' | 'type' | 'contactName' | 'leads' | 'status';
export default function PartnersListPage() {
  const navigate = useNavigate(); const user = useAuthStore((state) => state.user);
  const canCreate = user?.permissions.includes('partners.create') ?? false; const canEdit = user?.permissions.includes('partners.edit') ?? false;
  const [items, setItems] = useState<Partner[]>([]); const [total, setTotal] = useState(0); const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null);
  const [filters, setFilters] = useState<PartnerFilters>({ page: 1, pageSize: 20 }); const [sort, setSort] = useState<{ key: SortKey; direction: 'asc' | 'desc' }>({ key: 'name', direction: 'asc' });
  useEffect(() => { setLoading(true); partnersApi.list(filters).then((response) => { setItems(response.items); setTotal(response.total); }).catch((err) => setError(err instanceof Error ? err.message : 'Erro ao carregar parceiros.')).finally(() => setLoading(false)); }, [filters]);
  const sorted = useMemo(() => [...items].sort((a,b) => { const values = { name:[a.name,b.name], type:[PARTNER_TYPE_LABELS[a.type],PARTNER_TYPE_LABELS[b.type]], contactName:[a.contactName ?? '',b.contactName ?? ''], leads:[a._count.leads,b._count.leads], status:[a.status,b.status] }[sort.key]; const result = typeof values[0] === 'number' ? values[0] - (values[1] as number) : String(values[0]).localeCompare(String(values[1]), 'pt-BR'); return sort.direction === 'asc' ? result : -result; }), [items, sort]);
  function update(patch: Partial<PartnerFilters>) { setFilters((current) => ({ ...current, ...patch, page: 1 })); }
  function toggle(key: SortKey) { setSort((current) => ({ key, direction: current.key === key && current.direction === 'asc' ? 'desc' : 'asc' })); }
  const Header = ({ field, children }: { field: SortKey; children: string }) => <button onClick={() => toggle(field)} className="inline-flex items-center gap-1.5 hover:text-brand-purple">{children}<Icon name="sort" className={`h-3.5 w-3.5 ${sort.key === field ? 'text-brand-purple' : 'text-slate-300'}`} /></button>;
  return <AppShell><PageHeader eyebrow="Relacionamentos" title="Parceiros" description={`${total} parceiro${total === 1 ? '' : 's'} cadastrado${total === 1 ? '' : 's'} na rede comercial.`} actions={canCreate && <button className="btn-primary" onClick={() => navigate('/partners/novo')}><Icon name="plus" className="h-4 w-4" />Novo parceiro</button>} />
    <div className="filter-panel"><div className="grid gap-3 md:grid-cols-[1fr_220px_180px]"><div className="relative"><Icon name="search" className="absolute left-3.5 top-3.5 h-4 w-4 text-slate-400" /><input className="form-control pl-10" placeholder="Buscar por nome, documento ou contato..." value={filters.search ?? ''} onChange={(e) => update({ search: e.target.value || undefined })} /></div><select className="form-control" value={filters.type ?? ''} onChange={(e) => update({ type: (e.target.value || undefined) as PartnerFilters['type'] })}><option value="">Todos os tipos</option>{Object.entries(PARTNER_TYPE_LABELS).map(([value,label]) => <option key={value} value={value}>{label}</option>)}</select><select className="form-control" value={filters.status ?? ''} onChange={(e) => update({ status: (e.target.value || undefined) as PartnerFilters['status'] })}><option value="">Todos os status</option><option value="ACTIVE">Ativos</option><option value="INACTIVE">Inativos</option></select></div></div>
    {error && <p className="mb-4 rounded-xl border border-red-200 bg-red-50 p-3 text-sm text-red-600">{error}</p>}
    <div className="table-shell overflow-x-auto">{loading ? <p className="p-12 text-center text-sm text-slate-400">Carregando parceiros…</p> : <table className="data-table"><thead><tr><th><Header field="name">Parceiro</Header></th><th><Header field="type">Tipo</Header></th><th><Header field="contactName">Contato</Header></th><th><Header field="leads">Oportunidades</Header></th><th>Comissão</th><th><Header field="status">Status</Header></th><th className="text-right">Ações</th></tr></thead><tbody>{sorted.map((partner) => <tr key={partner.id}><td><button onClick={() => navigate(`/partners/${partner.id}`)} className="text-left"><p className="font-semibold text-slate-800 hover:text-brand-purple">{partner.name}</p><p className="mt-0.5 text-xs text-slate-400">{partner.document || partner.legalName || 'Documento não informado'}</p></button></td><td><span className="rounded-lg bg-purple-50 px-2.5 py-1 text-xs font-semibold text-brand-purple">{PARTNER_TYPE_LABELS[partner.type]}</span></td><td><p className="font-medium text-slate-700">{partner.contactName || '—'}</p><p className="text-xs text-slate-400">{partner.email || partner.phone}</p></td><td><span className="font-bold text-slate-700">{partner._count.leads}</span></td><td>{partner.commissionPercentage !== null ? `${Number(partner.commissionPercentage).toLocaleString('pt-BR')}%` : '—'}</td><td><span className={`inline-flex items-center gap-2 text-xs font-semibold ${partner.status === 'ACTIVE' ? 'text-emerald-600' : 'text-slate-400'}`}><span className={`status-dot ${partner.status === 'ACTIVE' ? 'bg-emerald-500' : 'bg-slate-300'}`} />{PARTNER_STATUS_LABELS[partner.status]}</span></td><td><div className="flex justify-end gap-1"><button className="icon-button" title="Visualizar" onClick={() => navigate(`/partners/${partner.id}`)}><Icon name="view" className="h-4 w-4" /></button>{canEdit && <button className="icon-button" title="Editar" onClick={() => navigate(`/partners/${partner.id}/editar`)}><Icon name="edit" className="h-4 w-4" /></button>}</div></td></tr>)}{sorted.length === 0 && <tr><td colSpan={7} className="py-14 text-center">Nenhum parceiro encontrado.</td></tr>}</tbody></table>}</div>
  </AppShell>;
}
